#!/bin/bash

filename=`basename "$1" | sed 's/\.[^.]*$//'`;
filepath="/websrv/content/secure/static/media/shows/$1";
remotepath="/secure/static/media/shows/$1";


mv "$1" "$filepath" && 
echo "move successful. adding to db..." &&
mysql -u eztheater -peztheater -e "INSERT INTO eztheater.Shows (name, path) VALUES('$filename', '$remotepath');" &&
echo "add successful.";





