#!/bin/bash

filename=`basename $1`;
filepath="/secure/static/media/shows/$filename";

mysql -u eztheater -peztheater -e "DELETE FROM eztheater.Shows WHERE path='$filepath'";

echo "If the deletion was successful, you can delete the file now..."
echo "Do this with \"rm /websrv/content$filepath\""
