#!/bin/bash

filename=`echo "$1" | sed 's/\.[^.]*$//'`;
filepath="/media/movies/$1";

mysql -u eztheater -peztheater -e "INSERT INTO eztheater.Movies (name, path) VALUES('$filename', '$filepath');";

mv "$1" "$2";


